# CMake generated Testfile for 
# Source directory: /Users/marcus/git/karbonit/tests/carbon
# Build directory: /Users/marcus/git/karbonit/tests/carbon
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-global_id "/Users/marcus/git/karbonit/bin/test-global_id")
set_tests_properties(test-global_id PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;8;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-archive-ops "/Users/marcus/git/karbonit/bin/test-archive-ops")
set_tests_properties(test-archive-ops PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;9;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-fix-map "/Users/marcus/git/karbonit/bin/test-fix-map")
set_tests_properties(test-fix-map PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;10;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-archive-iter "/Users/marcus/git/karbonit/bin/test-archive-iter")
set_tests_properties(test-archive-iter PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;11;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-archive-converter "/Users/marcus/git/karbonit/bin/test-archive-converter")
set_tests_properties(test-archive-converter PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;12;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-varuint "/Users/marcus/git/karbonit/bin/test-varuint")
set_tests_properties(test-varuint PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;13;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-mime "/Users/marcus/git/karbonit/bin/test-mime")
set_tests_properties(test-mime PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;14;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-json "/Users/marcus/git/karbonit/bin/test-json")
set_tests_properties(test-json PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;15;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-abstract-type-markers "/Users/marcus/git/karbonit/bin/test-abstract-type-markers")
set_tests_properties(test-abstract-type-markers PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;16;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-abstract-types-arrays "/Users/marcus/git/karbonit/bin/test-abstract-types-arrays")
set_tests_properties(test-abstract-types-arrays PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;17;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-abstract-types-columns "/Users/marcus/git/karbonit/bin/test-abstract-types-columns")
set_tests_properties(test-abstract-types-columns PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;18;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-abstract-types-objects "/Users/marcus/git/karbonit/bin/test-abstract-types-objects")
set_tests_properties(test-abstract-types-objects PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;19;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-printer-marker "/Users/marcus/git/karbonit/bin/test-printer-marker")
set_tests_properties(test-printer-marker PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;20;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-printer-json "/Users/marcus/git/karbonit/bin/test-printer-json")
set_tests_properties(test-printer-json PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;21;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-patch "/Users/marcus/git/karbonit/bin/test-carbon-patch")
set_tests_properties(test-carbon-patch PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;22;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-item "/Users/marcus/git/karbonit/bin/test-carbon-item")
set_tests_properties(test-carbon-item PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;23;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-arr-it "/Users/marcus/git/karbonit/bin/test-carbon-arr-it")
set_tests_properties(test-carbon-arr-it PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;24;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-obj-it "/Users/marcus/git/karbonit/bin/test-carbon-obj-it")
set_tests_properties(test-carbon-obj-it PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;25;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-from-json "/Users/marcus/git/karbonit/bin/test-carbon-from-json")
set_tests_properties(test-carbon-from-json PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;26;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-func-rec-exists "/Users/marcus/git/karbonit/bin/test-func-rec-exists")
set_tests_properties(test-func-rec-exists PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;27;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-func-rec-get "/Users/marcus/git/karbonit/bin/test-func-rec-get")
set_tests_properties(test-func-rec-get PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;28;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-func-rec-set "/Users/marcus/git/karbonit/bin/test-func-rec-set")
set_tests_properties(test-func-rec-set PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;29;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-1 "/Users/marcus/git/karbonit/bin/test-carbon-part-1")
set_tests_properties(test-carbon-part-1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;31;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-2 "/Users/marcus/git/karbonit/bin/test-carbon-part-2")
set_tests_properties(test-carbon-part-2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;32;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-3 "/Users/marcus/git/karbonit/bin/test-carbon-part-3")
set_tests_properties(test-carbon-part-3 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;33;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-4 "/Users/marcus/git/karbonit/bin/test-carbon-part-4")
set_tests_properties(test-carbon-part-4 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;34;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-5 "/Users/marcus/git/karbonit/bin/test-carbon-part-5")
set_tests_properties(test-carbon-part-5 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;35;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-6 "/Users/marcus/git/karbonit/bin/test-carbon-part-6")
set_tests_properties(test-carbon-part-6 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;36;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-7 "/Users/marcus/git/karbonit/bin/test-carbon-part-7")
set_tests_properties(test-carbon-part-7 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;37;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-8 "/Users/marcus/git/karbonit/bin/test-carbon-part-8")
set_tests_properties(test-carbon-part-8 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;38;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
add_test(test-carbon-part-9 "/Users/marcus/git/karbonit/bin/test-carbon-part-9")
set_tests_properties(test-carbon-part-9 PROPERTIES  _BACKTRACE_TRIPLES "/Users/marcus/git/karbonit/tests/CMakeLists.txt;12;add_test;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;39;CreateTest;/Users/marcus/git/karbonit/tests/carbon/CMakeLists.txt;0;")
